### ISSUE TITLE
通过Android studio profiler查看内存，发现thread hook没效果？

### ISSUE THREAD

**Issue by ZDfordream** [RicardoJiang/android-performance#1]
设置了pthread_attr_setstacksize，但看内存表现，实际没任何效果？

**Comment by RicardoJiang** [comment]
线程栈空间占的是虚拟内存，不会算到PSS里面，所以profiler里看不出来
我这边创建100个线程，虚拟内存大概增加了2000M，stackSize这个优化差不多可以省个50M，stackSize这个优化效果其实没那么明显

**Comment by Edison0716** [comment]
那种方式的内存优化效果明显？
