### ISSUE TITLE
GC 抑制 有问题 在我的 Vivo Y67A这个机型 试过了其他机型也有同样的问题

### ISSUE THREAD

**Issue by Edison0716** [RicardoJiang/android-performance#5]
![image](https://github.com/RicardoJiang/android-performance/assets/8669094/8707af93-fc58-4fcb-9ed9-f5208e4dab74)

**Comment by RicardoJiang** [comment]
现在的实现是有些问题，可以先看看这个实现：http://njuptrain.site/posts/GC/JIT-%E6%8A%91%E5%88%B6/
后面我修改下
